author: Atlas # 作者
description: Bfstack是个人技术网站，致力于前后端技术。目前博主主要集中于机器学习、深度学习、搜索、推荐技术;Coding Will Change The World, do not stop!!!
# keyword: 机器学习,machine learning,sklearn,深度学习,deep learning,搜索,search,lucene,推荐,resys
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Resys: /resys/
 Archives: /archives/
 Tags: /tags/
 Bookshelf: /bookshelf
 About: /about/


changyan: 
    app_id: cyteSvwmX
    conf: prod_e7ff572443e8d6b7e56013ccb8d536a8

# highlight
highlight:
  tomorrow

baidu_id: efdd0c828838577f503bb4e248582382

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: http://tva4.sinaimg.cn/crop.31.753.1838.1838.180/b7ba225djw1esoizj5nguj21kw23uu0x.jpg
  description: 我们所处的时代是最坏还是最好？！
  weibo_username: atlas2013
  github_username: atlas555
