author: Atlas # 作者
description: Code will change the world, and focus on search,recommend,deep learning.
keyword: resys, search, machine learning, deep learning
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Resys: /resys/
 Archives: /archives/
 Tags: /tags/
 Bookshelf: /bookshelf
 About: /about/


# highlight
highlight:
  tomorrow

# gitment
#gitment_owner: atlas555
#gitment_repo: atlas555.github.io/atlas555
#gitment_oauth_id: 0f87e490e00ee3fd87ef
#gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: efdd0c828838577f503bb4e248582382

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: http://tva4.sinaimg.cn/crop.31.753.1838.1838.180/b7ba225djw1esoizj5nguj21kw23uu0x.jpg
  description: 我们所处的时代是最坏还是最好？！
